---@meta
error("Cannot require a meta file")

_G.FzfLua = require("fzf-lua")

---@class fzf-lua.previewer.SwiperBase
---@field new function
---@field setup_opts function
---@field zero_cmd function?
---@field result_cmd function?
---@field preview_cmd function?
---@field highlight_matches function?
---@field win fzf-lua.Win

---@class fzf-lua.previewer.BufferOrFile
---@field match_id? integer

---@class fzf-lua.path.Entry
---@field stripped? string
---@field bufnr? integer
---@field line? integer
---@field col? integer
---@field bufname? string
---@field terminal? boolean
---@field path? string
---@field ctag? string
---@field uri? string
---@field range? lsp.Range
---@field debug? string debug information

---@class fzf-lua.buffer_or_file.Entry : fzf-lua.path.Entry, {}
---@field do_not_cache boolean?
---@field no_scrollbar boolean?
---@field buf_is_valid boolean?
---@field buf_is_loaded boolean?
---@field tick integer?
---@field fs_stat uv.fs_stat.result?
---@field no_syntax boolean?
---@field cached fzf-lua.buffer_or_file.Bcache?
---@field content string[]?
---@field filetype string?

---@class fzf-lua.keymap.Entry
---@field vmap string?
---@field mode string?
---@field key string?

---@class fzf-lua.buffer_or_file.Bcache
---@field bufnr? integer
---@field min_winopts? boolean
---@field invalid? boolean buffer content changed
---@field invalid_pos? boolean position changed
---@field tick? integer

---@alias fzf-lua.config.Action fzf-lua.ActionSpec|fzf-lua.shell.data2|fzf-lua.shell.data2[]|false
---@alias fzf-lua.config.Actions { [1]?: boolean, [string]: fzf-lua.config.Action }

---@class fzf-lua.ActionSpec
---@field [1] fzf-lua.shell.data2?
---@field fn? fzf-lua.shell.data2?
---@field exec_silent? boolean
---@field reload? boolean
---@field field_index? string
---@field desc? string
---@field prefix? string
---@field postfix? string
---@field reuse? boolean
---@field noclose? boolean
---@field _ignore? boolean

---@alias fzf-lua.profile "border-fused"|"borderless-full"|"borderless"|"cli"|"default-prompt"|"default-title"|"default"|"fzf-native"|"fzf-tmux"|"fzf-vim"|"hide"|"ivy"|"max-perf"|"skim"|"telescope"

---@class fzf-lua.Config: fzf-lua.config.Defaults,{}
---@field [1]? fzf-lua.profile|fzf-lua.profile[]
---@field [2]? boolean|integer
---@field defaults fzf-lua.config.Defaults|{}

---@class fzf-lua.config.Defaults: fzf-lua.config.Base,{}
---@field nbsp string
---@field winopts fzf-lua.config.Winopts
---@field keymap fzf-lua.config.Keymap
---@field actions table<string, fzf-lua.config.Actions>
---@field fzf_bin string?
---@field fzf_opts table<string, any>
---@field fzf_tmux_opts table<string, any>
---@field previewers fzf-lua.config.Previewers
---@field formatters table<string, any>
---@field files fzf-lua.config.Files
---@field global fzf-lua.config.Global
---@field git fzf-lua.config.Git
---@field grep fzf-lua.config.Grep
---@field grep_curbuf fzf-lua.config.GrepCurbuf
---@field args fzf-lua.config.Args
---@field oldfiles fzf-lua.config.Oldfiles
---@field quickfix fzf-lua.config.Quickfix
---@field quickfix_stack fzf-lua.config.QuickfixStack
---@field loclist fzf-lua.config.Loclist
---@field loclist_stack fzf-lua.config.LoclistStack
---@field buffers fzf-lua.config.Buffers
---@field tabs fzf-lua.config.Tabs
---@field lines fzf-lua.config.Lines
---@field blines fzf-lua.config.Blines
---@field treesitter fzf-lua.config.Treesitter
---@field spellcheck fzf-lua.config.Spellcheck
---@field tags fzf-lua.config.Tags
---@field btags fzf-lua.config.Btags
---@field colorschemes fzf-lua.config.Colorschemes
---@field highlights fzf-lua.config.Highlights
---@field awesome_colorschemes fzf-lua.config.AwesomeColorschemes
---@field helptags fzf-lua.config.Helptags
---@field manpages fzf-lua.config.Manpages
---@field lsp fzf-lua.config.Lsp
---@field diagnostics fzf-lua.config.Diagnostics
---@field builtin fzf-lua.config.Builtin
---@field profiles fzf-lua.config.Profiles
---@field marks fzf-lua.config.Marks
---@field changes fzf-lua.config.Changes
---@field jumps fzf-lua.config.Jumps
---@field tagstack fzf-lua.config.Tagstack
---@field commands fzf-lua.config.Commands
---@field autocmds fzf-lua.config.Autocmds
---@field command_history fzf-lua.config.CommandHistory
---@field search_history fzf-lua.config.SearchHistory
---@field serverlist fzf-lua.config.Serverlist
---@field registers fzf-lua.config.Registers
---@field keymaps fzf-lua.config.Keymaps
---@field nvim_options fzf-lua.config.NvimOptions
---@field spell_suggest fzf-lua.config.SpellSuggest
---@field filetypes fzf-lua.config.Filetypes
---@field packadd fzf-lua.config.Packadd
---@field menus fzf-lua.config.Menus
---@field tmux fzf-lua.config.Tmux
---@field dap fzf-lua.config.Dap
---@field complete_path fzf-lua.config.CompletePath
---@field complete_file fzf-lua.config.CompleteFile
---@field zoxide fzf-lua.config.Zoxide
---@field complete_line fzf-lua.config.CompleteLine
---@field file_icon_padding string
---@field dir_icon string
---@field __HLS fzf-lua.config.HLS
---@field [string] any

---@class fzf-lua.config.TreesitterWinopts
---@field enabled boolean
---@field fzf_colors? table<string, string>

---@class fzf-lua.config.PreviewOpts
---@field default? string
---@field border? any
---@field wrap? boolean
---@field hidden? boolean
---@field vertical? string
---@field horizontal? string
---@field layout? string
---@field flip_columns? integer
---@field title? any
---@field title_pos? "center"|"left"|"right"
---@field scrollbar? string
---@field scrolloff? integer
---@field delay? integer
---@field winopts? fzf-lua.config.PreviewerWinopts

---@class fzf-lua.config.PreviewerWinopts
---@field number? boolean
---@field relativenumber? boolean
---@field cursorline? boolean
---@field cursorlineopt? string
---@field cursorcolumn? boolean
---@field signcolumn? string
---@field list? boolean
---@field foldenable? boolean
---@field foldmethod? string
---@field scrolloff? integer
---@field winblend? integer

---@class fzf-lua.config.Keymap
---@field builtin? table<string, string>
---@field fzf? table<string, string>

---@class fzf-lua.SpawnStdioOpts
---@field debug? boolean
---@field profiler? boolean
---@field process1? boolean
---@field silent? boolean|integer
---@field cmd? string|string[]
---@field cwd? string
---@field cwd_only? boolean
---@field stdout? boolean
---@field stderr? boolean
---@field stderr_to_stdout? boolean
---@field formatter? fun(line:string):string|nil
---@field multiline? boolean
---@field git_dir? string
---@field git_worktree? string
---@field git_icons? boolean
---@field file_icons? boolean
---@field color_icons? boolean
---@field path_shorten? boolean
---@field absolute_path? boolean
---@field strip_cwd_prefix? boolean
---@field render_crlf? boolean
---@field exec_empty_query? boolean
---@field file_ignore_patterns? string[]
---@field rg_glob? boolean
---@field fn_transform? string|fun(line:string, opts: fzf-lua.SpawnStdioOpts):string|nil
---@field fn_preprocess? string|fun(opts: fzf-lua.SpawnStdioOpts):string[]|nil
---@field fn_postprocess? string|fun(opts: fzf-lua.SpawnStdioOpts):string[]|nil
---@field is_live? boolean
---@field contents? fzf-lua.content|fzf-lua.shell.data2
---@field __FZF_VERSION? string
---@field glob_flag? string
---@field glob_separator? string
---@field g? fzf-lua.SpawnStdioOpts.g
---@field no_ansi_colors? boolean

---@class fzf-lua.SpawnStdioOpts.g
---@field _fzf_lua_server? string
---@field _EOL? string
---@field _debug? boolean

---a basic config can be used by fzf_exec?
---generated from the result of `:=FzfLua.config.normalize_opts({}, {})`
---@class fzf-lua.config.Base
---@field cwd_prompt? boolean
---@field dir_icon? string
---@field enrich? fun(opts: fzf-lua.config.Resolved):fzf-lua.config.Resolved|{}
---@field fzf_bin? string
---@field fzf_colors? { [1]?: boolean, [string]: string? }
---@field fzf_opts? table<string, any>
---@field fzf_tmux_opts? table<string, any>
---@field hls? fzf-lua.config.HLS
---@field winopts? fzf-lua.config.Winopts|(fun(opts: fzf-lua.Config):fzf-lua.config.Winopts)
---@field keymap? fzf-lua.config.Keymap|(fun(opts: fzf-lua.Config):fzf-lua.config.Keymap)
---@field actions? fzf-lua.config.Actions|(fun(opts: fzf-lua.Config):fzf-lua.config.Actions)
---@field no_header? boolean
---@field no_header_i? boolean
---@field prompt? string
---@field cwd? string
---@field multiprocess? integer|boolean
---@field fn_transform? boolean|string|function
---@field fn_preprocess? boolean|string|function
---@field fn_postprocess? boolean|string|function
---@field file_icons? boolean|integer
---@field color_icons? boolean
---@field git_icons? boolean
---@field silent? boolean|integer
---@field previewer? fun(...)|table|string
---@field preview? string|function|table
---@field complete? (fun(s: string[], _o: fzf-lua.config.Resolved, l: string, c: integer):string?, integer?)|boolean
---@field header string
---@field query? string
---@field resume? boolean
---@field no_resume? boolean
---@field profile? string|table
---@field silent_fail? boolean
---@field rg_glob? boolean|integer
---@field headers? string[]
---@field cwd_prompt_shorten_len integer?
---@field cwd_prompt_shorten_val integer?
---@field header_prefix? string
---@field header_separator? string
---@field fn_selected function
---@field cb_co fun(co: thread)
---@field cwd_only boolean
---@field cmd? string
---@field debug? boolean|'v'|'verbose'
---@field preview_offset? string
---@field _fzf_cli_args? string[]
---@field __INFO? fzf-lua.Info
---@field __CTX? fzf-lua.Ctx|{}
---@field _normalized? boolean
---@field __call_fn? function
---@field __call_opts? table
---@field is_live? boolean is "live" picker
---@field contents? fzf-lua.content|fzf-lua.shell.data2
---@field _actions? fun():fzf-lua.config.Actions?
---@field __ACT_TO? function
---@field _start? boolean
---@field _is_skim? boolean
---@field _treesitter? (fun(line: string):string?,string?,string?,string?)|boolean?
---@field help_open_win? fun(buf: integer, enter: boolean, config: vim.api.keyset.win_config): integer
---@field autoclose? boolean
---@field line_field_index? string
---@field field_index_expr? string
---@field _ctag? string
---@field preview_pager? string

---@class fzf-lua.config.Resolved: fzf-lua.config.Base
---@field PidObject? table
---@field _headers? string[]
---@field _fmt? table
---@field pipe_cmd? string
---@field RIPGREP_CONFIG_PATH? string
---@field _ctx? fzf-lua.Ctx
---@field __FZF_VERSION? number[]
---@field __resume_key? function|string
---@field _cwd? string
---@field _type? "file"?
---@field _cached_hls? string[]
---@field _multiline? boolean
---@field __resume_set? function
---@field __resume_get? function
---@field _contents? string
---@field _is_fzf_tmux? boolean
---@field _is_skim? boolean
---@field __stringified? boolean
---@field __stringify_cmd? boolean
---@field __sigwinches? string[]
---@field __sigwinch_on_scope table<string, function>
---@field __sigwinch_on_any function[]
---
---@field process1? boolean
---@field profiler? boolean
---@field use_queue? boolean
---@field throttle? boolean
---@field env? boolean
---@field winopts? fzf-lua.config.Winopts
---@field _resume_reload? boolean
