name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rev: [nightly, v0.10.3]
        include:
          - os: ubuntu-latest
            install-deps: sudo apt-get update && sudo apt-get install -y fzf ripgrep fd-find
          - os: macos-latest
            install-deps: brew update && brew install fzf ripgrep fd
          - os: windows-latest
            install-deps: choco install fzf ripgrep fd

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Prepare
        run: |
          ${{ matrix.install-deps }}
          nvim --version
          fzf --version
          rg --version
          make prepare

      - name: Run tests
        run: |
          make test
